language: generic

service: docker

jobs:
  include:
    - stage: TEST
      script: 
            - cd webUI/mockServer
            - npm install
            - nohup npm start &
            - cd ../..
            - cd webUI/my-app
            - npm install
            - export CI=true
            - npm test
    - stage: TEST
      script: 
            - cd MarketCC
            - npm install
            - npm test
    - stage: TEST
      script: 
            - cd HospitalCC
            - npm install
            - npm test
    - stage: TEST
      script: 
            - cd blockchaine2e
            - git submodule init
            - cd fabric-samples
            - git checkout v1.4.4
            - curl -sS https://raw.githubusercontent.com/hyperledger/fabric/master/scripts/bootstrap.sh -o ./scripts/bootstrap.sh
            - chmod +x ./scripts/bootstrap.sh
            - ./scripts/bootstrap.sh 1.4.4 1.4.4 1.4.4
            #- docker pull hyperledger/fabric-couchdb:0.4.16
            #- docker tag hyperledger/fabric-couchdb:0.4.16 hyperledger/fabric-couchdb:latest
            - cd ..
            - cp ./byfn.sh ./fabric-samples/first-network
            - cd fabric-samples/first-network
            - ./byfn.sh up -n -i 1.4.4 -s couchdb
            - cd ../..
            - docker cp myscriptMarket.sh cli:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - cd ..
            - docker cp MarketCC cli:/opt/gopath/src/github.com/chaincode/
            - docker exec cli scripts/myscriptMarket.sh    
            - docker ps
            - docker logs dev-peer0.org1.example.com-MarketCC-1.0
            - docker logs peer0.org1.example.com
    - stage: TEST
      script: 
            - cd blockchaine2e
            - git submodule init
            - cd fabric-samples
            - git checkout v1.4.4
            - curl -sS https://raw.githubusercontent.com/hyperledger/fabric/master/scripts/bootstrap.sh -o ./scripts/bootstrap.sh
            - chmod +x ./scripts/bootstrap.sh
            - ./scripts/bootstrap.sh 1.4.4 1.4.4 1.4.4
            #- docker pull hyperledger/fabric-couchdb:0.4.16
            #- docker tag hyperledger/fabric-couchdb:0.4.16 hyperledger/fabric-couchdb:latest
            - cd ..
            - cp ./byfn.sh ./fabric-samples/first-network
            - cd fabric-samples/first-network
            - ./byfn.sh up -n -i 1.4.4 -s couchdb
            - cd ../..
            - docker cp myscripHospital.sh cli:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
            - cd ..
            - docker cp HospitalCC cli:/opt/gopath/src/github.com/chaincode/
            - docker exec cli scripts/myscripHospital.sh    
            - docker ps
            - docker logs dev-peer0.org1.example.com-HospitalCC-1.0
            - docker logs peer0.org1.example.com