language: generic

service: docker

jobs:
  include:
    - stage: TEST
      script: 
            - cd webUI/mockServer
            - npm install
            - nohup npm start &
            - cd ../..
            - cd webUI/my-app
            - npm install
            - export CI=true
            - npm test
    - stage: TEST
      script: 
            - cd JavaServer
            - nohup gradle runbootRun &
    - stage: TEST
      script: 
            - cd MarketCC
            - npm install
            - npm test
    - stage: TEST
      script: 
            - cd HospitalCC
            - npm install
            - npm test
    - stage: E2E TEST
      script: 
            - ./cicd.sh